### ISSUE TITLE
Add benchmark results to wiki

### ISSUE THREAD

**Issue by dazinator** [dazinator/DotNet.Glob#19]
As per request from @cocowalla

**Comment by Genbox** [comment]
It took more than an hour to run the benchmarks.
Since JIT32 is being replaced with RyuJIT32 and .NET Core is going to be the main platform, I think you could remove the CLR results.

I've attached the results from my machine in MarkDown format to this comment.

[results.zip](https://github.com/dazinator/DotNet.Glob/files/964706/results.zip)

**Comment by dazinator** [comment]
Thanks for this.
Not sure about removing CLR just yet, as still quite widely used? But maybe in future.
Definately open to anything that reduces runtime though. Many of those tests may not be that insightful. 
Also i'd love to get a graph produced, and I think BenchmarkDotNet has some sort of r# adaptor to produce graphs but I never got to investigating it.

**Comment by Genbox** [comment]
Sure, CLR is still used by most people out there. I just don't think it adds much value to benchmark both JIT and RyuJIT since characteristics are going to be similar in any case. I'd rather have quicker benchmarks with a simpler summary in the end, than a benchmark with a different compiler.

**Comment by dazinator** [comment]
Right - I have put these here: https://github.com/dazinator/DotNet.Glob/wiki/Benchmarks-(vs-Compiled-Regex)

Feel free to make any changes to the wiki page that you think improves it!

Also i'm open to any PR that improves the usefulness and runtime of the benchmarks!
Will close this issue now that we atleast have some up on the wiki.
