### ISSUE TITLE
Single asterisk behaviour

### ISSUE THREAD

**Issue by cocowalla** [dazinator/DotNet.Glob#25]
I seem to get odd results when using the single asterisk wildcard `*`. For example, let's take the following string:

`HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`

The pattern `*ave 12` matches, as expected, but `*ave*2` (which uses 2 asterisks) does not, neither doe `Shock* 12` (which uses a single asterisk, but not as the first character in the pattern).

Is this the expected behaviour? If so, what's the rationale behind it?

**Comment by dazinator** [comment]
Hmm I think this looks like a bug.

* should match any number of any characters, including none.

Would you perhaps, be able to add a couple of test cases to the existing unit tests that can we can then use to reproduce this? That will make it much speedier to resolve the problem

**Comment by dazinator** [comment]
Ok so this is what you should be seeing by design:

`Shock* 12` *should not* match `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`.
`*Shock* 12` *should not* match `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`.
`**\Shock* 12` *should* match `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`.
`*ave*2` *should not* match `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`.
`**\ave*2` *should* match `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`.

Basically the pattern is matched against the whole string, starting with the first token. A `*` will match any number of (including none) any characters in a single `segment`.

So `*` will not match `hi\there` because `*` only matches a single segment. Where as `**` behaves the same as `*` except it will also match any number of segments. So `**` will match `hi\there`.

I have just added test cases to the current development branch, and this seems to behave as desired.
What version of `dotnet.glob` are you currently using? 





 




 The pattern is matched to the whole string. So if you want the pattern to match the end of the string, you would have to use thisthat is desired behaviour. This is because

**Comment by dazinator** [comment]
I have added some unit tests covering these specific examples, and it looks like it is working by design in the latest release. The tests are here: https://github.com/dazinator/DotNet.Glob/blob/develop/src/DotNet.Glob.Tests/GlobTests.cs#L47-L49
and
https://github.com/dazinator/DotNet.Glob/blob/develop/src/DotNet.Glob.Tests/GlobTests.cs#L14-L16

**Comment by dazinator** [comment]
Am closing this for now, but feel free to comment further if you need more clarification. Might also be worth checking you are using atleast [version 1.5.0](https://www.nuget.org/packages/DotNet.Glob/1.5.0)

**Comment by cocowalla** [comment]
I'm using the 1.6 preview from 06- May. Will try upgrading to the latest preview layer and see if it still behaves the same.

**Comment by cocowalla** [comment]
Firstly, thanks for taking the time to write such a detailed description.

> `*` will match any number of (including none) any characters within a single `segment` only.

Given this, shouldn't `Shock* 12` match `Shockwave 12` from the last segment of `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`? (Especially since `*ave 12` does - or is this meant to *not* match?)

**Comment by dazinator** [comment]
*ave 12 is not meant to match. I think one of the unit tests I pointed to should cover that case.

**Comment by dazinator** [comment]
> Given this, shouldn't `Shock* 12` match `Shockwave 12` from the last segment of `HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Shockwave 12`?

It shouldnt match. `Shock* 12` means the string should start with the literal `Shock` then have 0 or many characters, then have the literal ` 12`. The string being matched starts with `H` so fails the match straight away. If you want to match the end of a string, and you dont care about the beginning, the pattern should start with `**\` as that will match any number (including 0) of any characters, any mumber of segments deep. So `**\Shock* 12` should match.

**Comment by cocowalla** [comment]
OK, I understand now; `*` is only really useful for matching filenames (or the last path segment for registry keys) if you're matching a path that doesn't contain directory separator characters, since `IsMatch` matches on the entire subject string. I think what I want to do then is: when glob patterns *don't* contain any directory separator characters, match on `Path.GetFileName(subject)`, otherwise match on the full path. But I get that isn't standard glob functionality, so I'll implement it in my application's code.

BTW, `*ave 12` definately matches in the preview version on NuGet.

**Comment by dazinator** [comment]
> BTW, `*ave 12` definately matches in the preview version on NuGet

Hmm ok thanks for letting me know.  I'll try and replicate it. So just to be clear, you are saying with the latest prerelease nuget package, the pattern `*ave 12` matches that shockwavw key local machine reg key? If thats correct ill see if I can reproduce this.

**Comment by cocowalla** [comment]
Yes (I just double-checked to be sure)

**Comment by dazinator** [comment]
Ok - have replicated this bug. Will fix in next release.

**Comment by dazinator** [comment]
@cocowalla  - this is now fixed if you upgrade to: https://www.nuget.org/packages/DotNet.Glob/1.6.0
