### ISSUE TITLE
Defect: Spaces After Comma Doesn't Match

### ISSUE THREAD

**Issue by MarkMichaelis** [dazinator/DotNet.Glob#31]
The following results seems to indicate a defect:

- `DotNet.Globbing.Glob.Parse("Stuff,*").IsMatch("Stuff, x");`: true
- `DotNet.Globbing.Glob.Parse("Stuff *").IsMatch("Stuff x");`: true
- `DotNet.Globbing.Glob.Parse("Stuff, *").IsMatch("Stuff, x");`: false

Am I missing something?

**Comment by dazinator** [comment]
Interesting.. looks like you may have found a bug there. Are you using the latest stable nuget version? If you have time to submit / add a failing test case to the tests project I'd be greatful. I'll take a look as soon as I can.

**Comment by MarkMichaelis** [comment]
It appears the issue is with the comma, not just the space:
`DotNet.Globbing.Glob.Parse("Stuff,X*").IsMatch("Stuff,Xx")'`: false

**Comment by dazinator** [comment]
Hmm

Does this match:

DotNet.Globbing.Glob.Parse("Stuff,X* ").IsMatch("Stuff,Xx")'`

?

**Comment by MarkMichaelis** [comment]
Fortunately, no.

**Comment by dazinator** [comment]
Or this:

DotNet.Globbing.Glob.Parse("Stuff,X* ").IsMatch("Stuff,Xx ")'`

**Comment by dazinator** [comment]
My guess (not at pc right now) is that it happens if:

1. The pattern ends in a *
2. The test string is the minimum length it can be for a successful match

Hence why above, If making the test string one char longer suddenly matches then it confirms my theory.

**Comment by dazinator** [comment]
Ok I see what is happening here. This is related to #32 

When unsupported alpha numeric characters are encountered in the token (comma is one of those i'm afraid) the parsing / tokeniser is skipping past that unsupported character so it's essentially like it's not there in the pattern.

In other words, when you do this:

`DotNet.Globbing.Glob.Parse("Stuff,*").IsMatch("Stuff, x");: true`

you are actually getting the result of this:

`DotNet.Globbing.Glob.Parse("Stuff*").IsMatch("Stuff, x");: true`

Because the comma in the pattern is being skipped over.

I need to think about how I address this. The first thing I should do is throw an exception if there is an unsupported character used in a token. If you don't mind I am going to close this in favour of #32
