### ISSUE TITLE
Escaping glob patterns

### ISSUE THREAD

**Issue by cocowalla** [dazinator/DotNet.Glob#51]
Is escaping glob patterns supported?

For example, let's say I have a literal path like:

`/my*files/more[stuff]/is-there-more?/`

Is there a supported mechanism my which `*`, `[`, `]` and `?` can be escaped, such that they will be treated as literals instead of glob characters? For example, can I escape characters with a backslash?

`/my\*files/more\[stuff\]/is-there-more\?/`

**Comment by cocowalla** [comment]
Fluent builder wouldn't work for my use case, as I need to parse arbitrary patterns (one I used was just an example).

Escaping with a backslash and only treating it as an escape sequence if followed by a special character sounds generally like the correct approach to me too.

There are some corner cases on Windows though. An example:

`C:\Test\[Te]st`

Is it a single folder named `C:\Test[Te]st` or is it `C:\Test` with a match on subfolders?

**Comment by cocowalla** [comment]
So, I thought I'd have a crack at this! I thought I was done, and was adding more test cases, then I realised that I don't think escaping with a backslash is going to work :(

Consider this pattern (which is likely to be very common):
`c:\MyFolder\*.txt`

The intent is of course to look for `*.txt` files within `c:\MyFolder`, but the asterisk would be treated as a literal, so that's not going to work.

Same deal:

`c:\MyFolder\[abc]de`

If we use backslash as an escape character, the result would be a literal `c:\MyFolder[abc]de`.

You might think that at least it's not an issue on Linux, but technically you can have backslashes in filenames (even if it's uncommon).

I'm not sure what a good solution is here. A simple solution is to make the escape character configurable, effectively pushing the problem to devs that use this library, but at least allowing them to choose something that works for their scenario.

**Comment by dazinator** [comment]
Yeah its tricky, thanks for having a go at it.

I was just reading how other glob libraries approach it and came across this https://docs.python.org/3/library/glob.html

It mentions:

> For a literal match, wrap the meta-characters in brackets. For example, '[?]' matches the character '?'.

:-)

**Comment by cocowalla** [comment]
Square brackets are glob characters tho?

**Comment by cocowalla** [comment]
Huh, that could be quite a clever solution! I'll give it a try tonight and see how it looks.

**Comment by dazinator** [comment]
@cocowalla 

I have done some more investigation on this, and it turns out that no logic changes are necessary for handling escaping.. It should already just work!

I added these test cases to `IsMatch` and they all pass, thanks to the existing character list parsing:

```
        [InlineData(@"C:\myergen\[[]a]tor", @"C:\myergen\[a]tor")]
        [InlineData(@"C:\myergen\[[]ator", @"C:\myergen\[ator")]
        [InlineData(@"C:\myergen\[[][]]ator", @"C:\myergen\[]ator")]
        [InlineData(@"C:\myergen[*]ator", @"C:\myergen*ator")]
        [InlineData(@"C:\myergen[*][]]ator", @"C:\myergen*]ator")]
        [InlineData(@"C:\myergen[*]]ator", @"C:\myergen*ator", @"C:\myergen]ator")]
        [InlineData(@"C:\myergen[?]ator", @"C:\myergen?ator")]
        [InlineData(@"/path[\]hatstand", @"/path\hatstand")]
        public void IsMatch(string pattern, params string[] testStrings)
```

I noted that one of the test cases you added I think you were expecting these to match:

`C:\myergen[*]]ator` pattern to match: `"C:\myergen*]ator")]`

This isn't actually how this is currently interpreted. The above pattern is actually still a character list, so it will expect to match any one character in that list, which means

`C:\myergen[*]]ator`  matches either `"C:\myergen*ator")]` or `"C:\myergen]ator")]`.

To match  `"C:\myergen*]ator")]` you would want to use this pattern:

`C:\myergen[*][]]ator` 

Hopefully that makes sense.

This feature should already work, but as part of the feature branch we need to just extend the README with a section explaining how escaping works. I'll get around to that at some point no doubt.

**Comment by dazinator** [comment]
Also negation also passes:

```
      [InlineData(@"/foo/bar[!!].baz", @"/foo/bar7.baz")] // anything except an exclaimation mark after bar
        [InlineData(@"/foo/bar[!]].baz", @"/foo/bar9.baz")] // anything except an ] after bar
        [InlineData(@"/foo/bar[!?].baz", @"/foo/bar7.baz")] // anything except an ? after bar
        [InlineData(@"/foo/bar[![].baz", @"/foo/bar7.baz")] // anything except an [ after bar

```

**Comment by cocowalla** [comment]
> The above pattern is actually still a character list, so it will expect to match any **_one_** character

^ emphasis mine :)  Yeah, I messed that one up!

> it turns out that no logic changes are necessary for handling escaping.. It should already just work!

Excellent 👍
