### ISSUE TITLE
Characters missing from list of allowable path characters

### ISSUE THREAD

**Issue by cocowalla** [dazinator/DotNet.Glob#52]
The readme says:

> By default, when your glob pattern is parsed, DotNet.Glob will only allow literals which are valid for path / directory names. These are:
> 
>     Any Letter (A-Z, a-z) or Digit
>     ., , !, #, -, ;, =, @, ~, _, :

Maybe I'm misunderstanding this section, but on all of Windows, Linux and MacOS, lot's of other characters are valid in file system paths, such as:

- Any printable Unicode character 你好！
- `{` `}` `[` `]` `(` `)` `+` `;` `%` `?` `*`

Also, on Windows `:` is *not* valid.

**Comment by dazinator** [comment]
Yeah you are right - this needs sorting.

Firstly the doc should say

- Any Letter or Digit

Not just A-Z, a-z or Digit. Because it actually does `Char.IsLetterOrDigit()`. So in your example for 你好！the first those characters return true for the IsLetterOrDigit check so they are currently allowed.

The last character however ！is categorised as unicode `punctuation` and so fails the current check for a valid literal.

However taken into a wider context - I don't think this limitation helps anything much and I think I should just remove it. Like you say the set of allowed characters will differ per platform and that's not something I want to get into really.

So here is what I think I should do:

1. Drop the set of allowed literal characters.
2. Remove the option `AllowInvalidPathCharacters`.

The default behaviour will then just be that the character will be assumed to be a literal if it isn't parsed as any other token first - which is how `AllowInvalidPathCharacters`= true behaves.

**Comment by cocowalla** [comment]
Yep, treating anything that isn't a special character as a literal makes sense to me

**Comment by dazinator** [comment]
Thanks @cocowalla  this will be releases in `2.1.0`
