### ISSUE TITLE
Is the * operator greedy or non-greedy?

### ISSUE THREAD

**Issue by snielsson** [dazinator/DotNet.Glob#55]
In other words, does it make the longest possible or shortest possible match?

Is it possible to specify a non-greedy (like *? in regex) in case it is greedy ?

**Comment by dazinator** [comment]
This is slightly tricky to describe, but I think the answer you are looking for is: it's non greedy. But to be clear let me explain how it works in more detail.

When `*` is evaluated, it matches a single character at a time from the string at the present position, advancing the current position one place at a time. Each time it advances, the remaining token/s in the pattern are given a chance to evaluate at this new position. If they now match, then the * stops consuming and its match is complete at that position.

This is complicated by the fact that there are some heuristics and special casing. For example, suppose the pattern is `*xyz[a-z]`. In this case, the remaining pattern (after the initial `*`) matches a fixed length of 4 chacters. Therefore when matching a string such as `fooooooooxyzh` the `*` character already knows that it can consume immediately all characters upto the last 4 characters from the end of the string, before it attempts to let the remaining tokens (`xyz[a-z]`) perform their match at that position. I beleive you would still refer to this as a non greedy match, just with some heuristics to eliminate unnecessary computation in special cases.

In addition to tokens that match a `fixed` length, some patterns its possible to see that there is no fixed lenght but there is a minimum length. For example, when the first `*` is matched from the pattern `*foo/**/*bar.baz` it knows that the remainder of the pattern matches a minimum length string of 11 in length. Therefore it will advance one character at a time, but it won't try to advance past the point in the string where there are less than 11 characters remaining, because it knows at that point, it's a failure.

Does this help?

**Comment by dazinator** [comment]
@snielsson - hopefully this has answered your question, i'll close for now. Let me know if not.
