### ISSUE TITLE
How to achieve starts with?

### ISSUE THREAD

**Issue by kunalkaroth** [dazinator/DotNet.Glob#57]
I want to do something like: 
If the string starts with # then process accordingly: 
for e.g., 
#this is a comment
##this is a comme%$\/@##
#this is a comment#

I don't care what follows after the first '**#**'. How do I achieve starts with?

For now, it seems that .OneOf('#') looks for instances of '#' and rightly so.  

new GlobBuilder().OneOf('#').ToGlob(defaultGlobOptions).IsMatch(globLine)

Is there a way to do, GlobBuilder().**StartsWith**('#')

**Comment by geekstew** [comment]
Actually another problem is matching this:
\\#test3\\*
I've tried:
new GlobBuilder().OneOf('\\').OneOf('!', '#').Wildcard()
and 
new GlobBuilder().OneOf('\\').OneOf('!', '#').Wildcard().PathSeperator(PathSeperatorKind.BackwardSlash).DirectoryWildcard()

**Comment by dazinator** [comment]
@geekstew thanks for raising this.

One thing I am curious about - why not just use `string.StartsWith()` ? :-)

If you want to match a string that starts with `#` or `!` using a glob, you could try:

`[#!]*`

This will match strings like `#test3` or `#this is a comment` but it will not match string's that have additional path separators like `#test3\` or `#test3\foo` because a `*` will only match upto a path seperator it won't match `/` or `\`. 

So if your strings are also likely to contain `\` and `/` seperators you would need to use `**` because that can match past seperators.

So here is the revised pattern for that:

 `[#!]*\**`

That should match any string starting with `#` or `!` with zero or more path seperators `/` or `\`.

Note when testing this I found a bug. The above pattern actually only currently matches any string starting with `#` or `!` with **one** or more path seperators. I will release a fix for this to nuget soon.

Lastly, if there is a chance your input strings may also start zero or many path seperators before the `#` or `!` i.e `/#foo` or `fooawd/var#awwda` or `#fooo` and you wan't to match that too then here is a revised pattern to cater for this:

 `**\[#!]*\**`

This basically now says the input string can start with any number of path segments `\` before matching on the `#` or `!`.

Hopefully this helps.

So in order to build this pattern with the builder you want:

```
  var glob = new GlobBuilder()
               .DirectoryWildcard(null, PathSeperatorKind.BackwardSlash)
               .OneOf('#', '!')
               .Wildcard()
               .DirectoryWildcard(PathSeperatorKind.BackwardSlash, null)      
               .ToGlob();

```

Note when calling `DirectoryWildcard()` the `PathSeperatorKind` that you pass in represent the leading or trailing path seperators surrounding the ** in the pattern. So the builder above builds this: `**\[#!]*\**`

**Comment by geekstew** [comment]
Thanks for fixing the bug! :) 
I don't want to use .StartsWith because there are often cases where something else is to be done in conjunction. Keeping one way of doing things keeps code clean and consistent. 
I noticed that I can now do the following (of course with the corresponding glob object model constructs). 

^#                       -> [#]*\** 
^!{1}[\\]{1}(!|#)    ->  [!]\[!#]*\**
^!{1}                   ->  [!]*\**
^\\{1}(!|#)           ->  [\\][!#]*\**

**Comment by dazinator** [comment]
Cool. My Regex isn't great :-)
By the way, just be careful with `[!#]`. Not sure if you were aware but an `!` as the first character in a character list, actually stands for a negation - i.e it means match any character that's not in the specified character list. So `[!#]` means match any character as long as it isn't a `#`.

If you don't want negation behaviour in a character list, don't put the `!` first, i.e `[#!]` means match either a `#` or ` !`.

Character list and negation is explained on the README, as well as some information about escaping https://github.com/dazinator/DotNet.Glob#escaping-special-characters however I don't think I have mentioned this nuance anywhere - should probably add that to the readme :-)
