### ISSUE TITLE
Matching partial paths?

### ISSUE THREAD

**Issue by LordMike** [dazinator/DotNet.Glob#86]
Hi - awesome project. I'm using it in some smallish hobby things right now to try it out.

I'm wondering how to go about matching partial paths. So if I were to match `C:\Alpha\Beta\Charlie.txt` with the glob `Beta/**`, I think I need to tweak my glob to be `**/Beta/**` (my current code just prefixes `**/`).

Is there an intended way to match partial paths?

In my use case, the user will work from some directory (like working directory), and everything is going to be relative from there. I also imagine other use cases, like emulating git ignore and its matching would require partial matches.

**Comment by dazinator** [comment]
Thanks!

Technically having '**/' at the start is the correct way to match any starting portion. However perhaps there are ways to set up your application to avoid working with full paths to begin with so that you are in fact only ever matching against relative paths anyway. This may be more efficient.

The typical way net core (and .net 5) deals with this sort of thing is via an IFileProvider abstraction provided by the Microsoft.Extensions.FileProvider.* nuget packages. For example there is a PhysicalFileProvider that you create with a root directory (i.e the working directory in your case) and then when you want to read a file you only supply the relative path. For example `fileprovider.GetFile("foo.txt")` would return the FileInfo for the foo.txt file relative to the file providers root directory. You can also get information about directories etc. If your application gets file and directory information using a FileProvider then you will have relative file paths to begin with. Therefore when matching files you can match against relative paths and won't need to use a wildcard prefix.

So yes the globbing spec does provided a way to Match partial paths and it's as you guessed, but it's also possible in many apps to work with relative file path information and match purely against those relative paths in which case you won't need to. Its not really a DotNet.Glob concern which you do.

Hope that helps!

**Comment by LordMike** [comment]
Right. I'll see if I can't tweak it to work on relative paths - I fear there will be cases when it becomes a full path anyways. 

But thanks! :)
It helped.

**Comment by rbeurskens** [comment]
Not sure if I should post this here, and if it's considered a 'necro' .. but I wrote my own filesystem matcher (over [Testably.Abstractions](https://github.com/Testably/Testably.Abstractions), but that should not make a difference) because Microsoft's `Extensions.FileSystemGlobbing` supports too little glob features for me (even not the '?' wildcard). Then, I found out about `Dazinator.Extensions.FileProvider`, which i could have used instead of writing my own. But comparing the implementations, there are some things in my implementation that might be useful to share if desired.:

I use a similar traversing algorithm for recursive traversal, but I have included a check if a subfolder should even be traversed based on the include and exclude globs, which could reduce a lot of I/O on a physical disk, especially with a large file structure if no include can match anything in the folder or any exclude would match everything in the folder. For this I added a method to `Glob` to make it able to determine relevance based on a given subdirectory (`IsRelevantForDirectory`) and another to check if it would match everything in a given subdirectory. (As `Glob` is optimal and really fast for full matching, but currently does not support partial/incremental/segment-based matching, like what Microsoft's `Matcher` uses internally to avoid matching of redundant pattern (segments) and early exclusion for subfolders.)
With that addition, I included a call to this method from the tarversal loop before pushing the subdirectory onto the stack:
If you're interested, I could create a PR for the additional methods in `Glob`. 
```C#
    internal static bool ShouldTraverseDirectory<T>(StringOrSpan relativePath, int offset, int depth, T includeGlobs, T excludeGlobs)
        where T : IReadOnlyList<Glob> 
    {
        var entryName = relativePath[offset..];

        // Check if the directory is relevant for any include glob (relevant => it could match ANY file in the directory)
        bool shouldEnqueue = false;
        for (int i = 0; i < includeGlobs.Count; i++)
            if (includeGlobs[i].IsRelevantForDirectory(entryName, depth))
            {
                shouldEnqueue = true;
                break;
            }

        if (!shouldEnqueue)
            return false;

        // Check if the directory is fully excluded by any exclude glob (any glob matches ALL content in the directory)
        // This is an (optional) relatively expensive check, but it can avoid traversing entire subtrees and checking all containing files one by one.
        for (int i = 0; i < excludeGlobs.Count; i++)
            if (excludeGlobs[i].MatchesAllContentInDirectory(relativePath, depth))
            {
                shouldEnqueue = false;
                break;
            }

        return shouldEnqueue;
    }
```
