### ISSUE TITLE
Inconsistent Matching

### ISSUE THREAD

**Issue by majora2007** [dazinator/DotNet.Glob#91]
After testing out this library, I'm feeling like I don't understand how this library works. 

I have the following example:
```
var pattern = @"*Accel World/*";
var file = "C:/Data/Accel World/Specials/Accel World SP01.cbz";

Console.WriteLine($"{file} {Glob.Parse(pattern).IsMatch(file)}");

file = "C:/Data/hello.pdf";
Console.WriteLine($"{file} {Glob.Parse(pattern).IsMatch(file)}");
```

I would expect that the first would return True and the second would return False, but I get:

```
C:/Data/Accel World/Specials/Accel World SP01.cbz False
C:/Data/hello.pdf False
```

Am I missing something about how the library works? 

For good measure:
```
var pattern = @"*.*";
var file = "C:/Data/Accel World/Specials/Accel World SP01.cbz";

Console.WriteLine($"{file} {Glob.Parse(pattern).IsMatch(file)}");

file = "C:/Data/hello.pdf";
Console.WriteLine($"{file} {Glob.Parse(pattern).IsMatch(file)}");

C:/Data/Accel World/Specials/Accel World SP01.cbz False
C:/Data/hello.pdf False

```

**Comment by dazinator** [comment]
Yeah so `*` will only match upto a path seperator, no further.

So your first example `*Accel World/*` - that first `*` only matches `C:/` so `/Data` is not matched.

You can deal with this in two ways.

1. Use `**` - e.g `**/*Accel World/*` - this should work because - read the readme page of this repo on `**`
2. In your application code, strip the base path from the string your are testing before matching.. this may or may not be suitable for your use case I'm not sure. Basic idea is, if all paths your are testing begin `C:/foo/` and your application knows that this is the case prior to building the glob pattern, then it can strip `C:/foo` base path from every test string - converting it to a relative path basically, and the use glob patterns that match on this relative path - like `*Accel World/*` which would now match against the test string `/jsjdjdjAccel World/fomsjfje` because you removed the `C:/foo` base portion of it prior to evaluation.

**Comment by majora2007** [comment]
Okay, I misunderstood the upto a path separator. 

Okay, after messing around and refactoring for your idea of stripping the root of the path away, I was able to get a working solution. 

In case anyone runs into this while parsing files, this is my approach:
```
var foundFiles = _directoryService.GetFilesWithCertainExtensions(folderPath,
                        Parser.Parser.SupportedExtensions, SearchOption.TopDirectoryOnly)
                    .Select(file => _directoryService.FileSystem.FileInfo.FromFileName(file).Name)
                    .Where(fileName => !matcher.ExcludeMatches(fileName));
```

Essentially for each file, strip everything but the file name out and match. For handling directories, that is done in the same manner (above since we are recursively expanding).
```
var directories = _directoryService.GetDirectories(folderPath)
                .Select(folder => _directoryService.FileSystem.DirectoryInfo.FromDirectoryName(folder).Name + _directoryService.FileSystem.Path.AltDirectorySeparatorChar)
                .Where(folderName => !matcher.ExcludeMatches(folderName));
```

Appreciate again the quick response.
